export const GET_IN_PRODUCTS_REQUEST = 'GET_IN_PRODUCTS_REQUEST';
export const GET_IN_PRODUCTS_SUCCESS = 'GET_IN_PRODUCTS_SUCCESS';
export const GET_IN_PRODUCTS_FAILURE = 'GET_IN_PRODUCTS_FAILURE';

export const GET_OUT_PRODUCTS_REQUEST = 'GET_OUT_PRODUCTS_REQUEST';
export const GET_OUT_PRODUCTS_SUCCESS = 'GET_OUT_PRODUCTS_SUCCESS';
export const GET_OUT_PRODUCTS_FAILURE = 'GET_OUT_PRODUCTS_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_IN_REQUEST = 'UPDATE_PRODUCT_IN_REQUEST';
export const UPDATE_PRODUCT_IN_SUCCESS = 'UPDATE_PRODUCT_IN_SUCCESS';
export const UPDATE_PRODUCT_IN_FAILURE = 'UPDATE_PRODUCT_IN_FAILURE';

export const UPDATE_PRODUCT_OUT_REQUEST = 'UPDATE_PRODUCT_OUT_REQUEST';
export const UPDATE_PRODUCT_OUT_SUCCESS = 'UPDATE_PRODUCT_OUT_SUCCESS';
export const UPDATE_PRODUCT_OUT_FAILURE = 'UPDATE_PRODUCT_OUT_FAILURE';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const CREATE_PRODUCT_NAME_REQUEST = 'CREATE_PRODUCT_NAME_REQUEST';
export const CREATE_PRODUCT_NAME_SUCCESS = 'CREATE_PRODUCT_NAME_SUCCESS';
export const CREATE_PRODUCT_NAME_FAILURE = 'CREATE_PRODUCT_NAME_FAILURE';



