# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = [
  [1, 'Pain'],
  [2, 'Fruits'],
  [3, 'Légumes'],
  [4, 'Fruits secs'],
  [5, 'Entretien & nettoyage'],
  [6, 'Higiène'],
  [7, 'Boissons'],
  [8, 'Conserves & bocaux'],
  [9, 'Féculents'],
  [10, 'Apéritif'],
  [11, 'Huiles, vinaigres & vinaigrettes'],
  [12, 'Epices'],
  [13, 'Saveurs du monde'],
  [14, 'Sucre, farine & préparation de gâteaux'],
  [15, 'Chocolats & bonbons'],
  [16, 'Biscuits & gâteaux'],
  [17, 'Compotes'],
  [18, 'Petit déjeuner'],
  [19, 'Crèmerie'],
  [20, 'Viandes & poissons'],
  [21, 'Traiteur'],
  [22, 'Surgelés']
]

produits = [
  ['Pains au lait', 1],
  ['Pain de mie', 1],
  ['Brioche', 1],
  ['Bananes', 2],
  ['Pommes', 2],
  ['Poires', 2],
  ['Ananas', 2],
  ['Oranges', 2],
  ['Kiwis', 2],
  ['Kakis', 2],
  ['Citrons jaunes', 2],
  ['Citrons verts', 2],
  ['Fraises', 2],
  ['Cerises', 2],
  ['Fruits de la passion', 2],
  ['Pamplemousses', 2],
  ['Mangues', 2],
  ['Clémentines', 2],
  ['Grenades', 2],
  ['Pêches', 2],
  ['Melon', 2],
  ['Raisin', 2],
  ['Framboises', 2],
  ['Nectarines', 2],
  ['Courgettes', 3],
  ['Concombres', 3],
  ['Carottes', 3],
  ['Pommes de terre', 3],
  ['Poivrons', 3],
  ['Oignons', 3],
  ['Ails', 3],
  ['Tomates', 3],
  ['Echalottes', 3],
  ['Poireaux', 3],
  ['Navets', 3],
  ['Champignons', 3],
  ['Endives', 3],
  ['Betteraves', 3],
  ['Avocats', 3],
  ['Artichauts', 3],
  ['Radis', 3],
  ['Chou blanc', 3],
  ['Chou fleur', 3],
  ['Brocolis', 3],
  ['Choux de bruxelles', 3],
  ['Salade', 3],
  ['Asperges', 3],
  ['Patates douces', 3],
  ['Olives', 3],
  ['Noix', 4],
  ['Amandes', 4],
  ['Noisettes', 4],
  ['Bicarbonate de soude', 5],
  ['Vinaigre blanc', 5],
  ['Lessive', 5],
  ['Adoucissant', 5],
  ['Tablettes lave vaisselle', 5],
  ['Liquide vaiselle', 5],
  ['Sel regénérant', 5],
  ['Dépoussiérant', 5],
  ['Nettoyant vitres', 5],
  ['Nettoyant sol', 5],
  ['Papier toilette', 5],
  ['Essuie tout', 5],
  ['Dentifrice', 6],
  ['Lingettes intimes', 6],
  ['Tampons', 6],
  ['Serviettes hygiéniques', 6],
  ['Bières', 7],
  ['Pepsi', 7],
  ['Sirop', 7],
  ['Vin', 7],
  ['Haricots verts', 8],
  ['Artichauts', 8],
  ['Olives', 8],
  ['Thon', 8],
  ['Maqueraux', 8],
  ['Lentilles', 8],
  ['Petits pois et carottes', 8],
  ['Maïs', 8],
  ['Pois chiches', 8],
  ['Asperges', 8],
  ['Coulis de tomate', 8],
  ['Pulpes de tomate', 8],
  ['Mogettes', 8],
  ['Chataîgnes', 8],
  ['Champignons', 8],
  ['Tagliatelles', 9],
  ['Spaghettis', 9],
  ['Penne', 9],
  ['Linguine', 9],
  ['Riz blanc', 9],
  ['Riz noir', 9],
  ['Riz sauvage', 9],
  ['Semoule', 9],
  ['Quinoa', 9],
  ['Boulghour', 9],
  ['Chips', 10],
  ['Pistaches', 10],
  ['Olives', 10],
  ['Huile d\'olive', 11],
  ['Vinaigre balsamique', 11],
  ['Sel fin', 12],
  ['Gros sel', 12],
  ['Poivre', 12],
  ['Muscade', 12],
  ['Cannelle', 12],
  ['Aneth', 12],
  ['Persil', 12],
  ['Basilic', 12],
  ['Cumin', 12],
  ['Bouillons de légumes', 12],
  ['Lupins', 13],
  ['Fajitas', 13],
  ['Nouilles chinoises', 13],
  ['Farine', 14],
  ['Sucre', 14],
  ['Cassonade', 14],
  ['Sucre glace', 14],
  ['Levure chimique', 14],
  ['Sucre vanillée', 14],
  ['Vanille', 14],
  ['Chocolat noir dessert', 15],
  ['Chocolat à déguster', 15],
  ['Barres de céréales', 16],
  ['Cookies', 16],
  ['Petits écoliers', 16],
  ['Granola', 16],
  ['M&ms', 16],
  ['Madeleines', 16],
  ['Compotes', 17],
  ['Céréales', 18],
  ['Miel', 18],
  ['Confiture', 18],
  ['Pâte à tartiner', 18],
  ['Chocolat en poudre', 18],
  ['Café', 18],
  ['Thé', 18],
  ['Biscottes', 18],
  ['Oeufs', 19],
  ['Lait de vache', 19],
  ['Lait de coco', 19],
  ['Crème fraîche', 19],
  ['Yaourts', 19],
  ['Fromage', 19],
  ['Beurre', 19],
  ['Saumon', 20],
  ['Cabillaud', 20],
  ['Crevettes', 20],
  ['Saumon fumé', 20],
  ['Jambon cru', 20],
  ['Lardons fumés', 20],
  ['Gnocchis', 21],
  ['Pattes fourées', 21],
  ['Pattes fraîches', 21],
  ['Pâte à pizza', 21],
  ['Pâte feuilletée', 21],
  ['Pâte brisée', 21],
  ['Raviolis', 21],
  ['Pommes noisettes', 22],
  ['Légumes', 22],
  ['Pizzas', 22]
]

categories.each do |id, name|
  Category.create!(id: id, name: name)
end

produits.each do |name, category|
  ProductName.create!(name: name, category_id: category)
end

ProductName.all.each do |p|
  Product.create!(name: p.name, product_name_id: p.id, category_id: p.category_id)
end