export const GET_LISTS_REQUEST = 'GET_LISTS_REQUEST';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';

export const GET_LIST_EDIT_REQUEST = 'GET_LIST_EDIT_REQUEST';
export const GET_LIST_EDIT_SUCCESS = 'GET_LIST_EDIT_SUCCESS';
export const GET_LIST_EDIT_FAILURE = 'GET_LIST_EDIT_FAILURE';

export const UPDATE_LIST_REQUEST = 'UPDATE_LIST_REQUEST';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAILURE = 'UPDATE_LIST_FAILURE';

export const GET_LISTS_PRODUCTS_REQUEST = 'GET_LISTS_PRODUCTS_REQUEST';
export const GET_LISTS_PRODUCTS_SUCCESS = 'GET_LISTS_PRODUCTS_SUCCESS';
export const GET_LISTS_PRODUCTS_FAILURE = 'GET_LISTS_PRODUCTS_FAILURE';
