export const GET_LISTS_REQUEST = 'GET_LISTS_REQUEST';
export const GET_LISTS_SUCCESS = 'GET_LISTS_SUCCESS';
export const GET_LISTS_FAILURE = 'GET_LISTS_FAILURE';

export const LOAD_MORE_LISTS_REQUEST = 'LOAD_MORE_LISTS_REQUEST';
export const LOAD_MORE_LISTS_SUCCESS = 'LOAD_MORE_LISTS_SUCCESS';
export const LOAD_MORE_LISTS_FAILURE = 'LOAD_MORE_LISTS_FAILURE';

export const RESET_LISTS = 'RESET_LISTS';

export const GET_USER_LISTS_INFO_REQUEST = 'GET_USER_LISTS_INFO_REQUEST';
export const GET_USER_LISTS_INFO_SUCCESS = 'GET_USER_LISTS_INFO_SUCCESS';
export const GET_USER_LISTS_INFO_FAILURE = 'GET_USER_LISTS_INFO_FAILURE';

export const CREATE_LIST_REQUEST = 'CREATE_LIST_REQUEST';
export const CREATE_LIST_SUCCESS = 'CREATE_LIST_SUCCESS';
export const CREATE_LIST_FAILURE = 'CREATE_LIST_FAILURE';

export const GET_LIST_REQUEST = 'GET_LIST_REQUEST';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const GET_LIST_FAILURE = 'GET_LIST_FAILURE';

export const GET_USER_LIST_REQUEST = 'GET_USER_LIST_REQUEST';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';

export const LOAD_MORE_USER_LIST_REQUEST = 'LOAD_MORE_USER_LIST_REQUEST';
export const LOAD_MORE_USER_LIST_SUCCESS = 'LOAD_MORE_USER_LIST_SUCCESS';
export const LOAD_MORE_USER_LIST_FAILURE = 'LOAD_MORE_USER_LIST_FAILURE';

export const RESET_LIST = 'RESET_LIST';

export const GET_LIST_EDIT_REQUEST = 'GET_LIST_EDIT_REQUEST';
export const GET_LIST_EDIT_SUCCESS = 'GET_LIST_EDIT_SUCCESS';
export const GET_LIST_EDIT_FAILURE = 'GET_LIST_EDIT_FAILURE';

export const GET_LISTS_WITHOUT_USER_REQUEST = 'GET_LISTS_WITHOUT_USER_REQUEST';
export const GET_LISTS_WITHOUT_USER_SUCCESS = 'GET_LISTS_WITHOUT_USER_SUCCESS';
export const GET_LISTS_WITHOUT_USER_FAILURE = 'GET_LISTS_WITHOUT_USER_FAILURE';

export const UPDATE_LIST_REQUEST = 'UPDATE_LIST_REQUEST';
export const UPDATE_LIST_SUCCESS = 'UPDATE_LIST_SUCCESS';
export const UPDATE_LIST_FAILURE = 'UPDATE_LIST_FAILURE';

export const ADD_USER_TO_LIST_REQUEST = 'ADD_USER_TO_LIST_REQUEST';
export const ADD_USER_TO_LIST_SUCCESS = 'ADD_USER_TO_LIST_SUCCESS';
export const ADD_USER_TO_LIST_FAILURE = 'ADD_USER_TO_LIST_FAILURE';

export const ADD_USERS_TO_LIST_REQUEST = 'ADD_USERS_TO_LIST_REQUEST';
export const ADD_USERS_TO_LIST_SUCCESS = 'ADD_USERS_TO_LIST_SUCCESS';
export const ADD_USERS_TO_LIST_FAILURE = 'ADD_USERS_TO_LIST_FAILURE';

export const SEND_MESSAGE_FROM_LIST_REQUEST = 'SEND_MESSAGE_FROM_LIST_REQUEST';
export const SEND_MESSAGE_FROM_LIST_SUCCESS = 'SEND_MESSAGE_FROM_LIST_SUCCESS';
export const SEND_MESSAGE_FROM_LIST_FAILURE = 'SEND_MESSAGE_FROM_LIST_FAILURE';

export const SEND_SMS_FROM_LIST_REQUEST = 'SEND_SMS_FROM_LIST_REQUEST';
export const SEND_SMS_FROM_LIST_SUCCESS = 'SEND_SMS_FROM_LIST_SUCCESS';
export const SEND_SMS_FROM_LIST_FAILURE = 'SEND_SMS_FROM_LIST_FAILURE';

export const DELETE_LIST_REQUEST = 'DELETE_LIST_REQUEST';
export const DELETE_LIST_SUCCESS = 'DELETE_LIST_SUCCESS';
export const DELETE_LIST_FAILURE = 'DELETE_LIST_FAILURE';

export const DELETE_USERS_FROM_LIST_REQUEST = 'DELETE_USERS_FROM_LIST_REQUEST';
export const DELETE_USERS_FROM_LIST_SUCCESS = 'DELETE_USERS_FROM_LIST_SUCCESS';
export const DELETE_USERS_FROM_LIST_FAILURE = 'DELETE_USERS_FROM_LIST_FAILURE';
