export const GET_CATEGORIES_REQUEST = 'GET_CATEGORIES_REQUEST';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';

export const GET_PRODUCTS_NOT_IN_LIST_REQUEST = 'GET_PRODUCTS_NOT_IN_LIST_REQUEST';
export const GET_PRODUCTS_NOT_IN_LIST_SUCCESS = 'GET_PRODUCTS_NOT_IN_LIST_SUCCESS';
export const GET_PRODUCTS_NOT_IN_LIST_FAILURE = 'GET_PRODUCTS_NOT_IN_LIST_FAILURE';

export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILURE = 'CREATE_CATEGORY_FAILURE';